# Generated by Django 6.0 on 2026-01-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
