# Generated by Django 5.2.4 on 2025-07-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_merge_0003_populate_slugs_0004_fix_missing_slugs'),
    ]

    operations = [
    ]
